targets = [
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
unmaintained = "deny"
yanked = "deny"
ignore = [
    "RUSTSEC-2019-0031",
]

[licenses]
# The lint level for crates which do not have a detectable license
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "MIT",
    #"Apache-2.0 WITH LLVM-exception",
]
copyleft = "deny"
exceptions = [
    { allow = ["Zlib"], name = "adler32" },
    { allow = ["ISC", "MIT", "OpenSSL"], name = "ring" },
    { allow = ["ISC"], name = "untrusted" },
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "deny"
deny = [
    # Each entry the name of a crate and a version range. If version is
    # not specified, all versions will be matched.
    #{ name = "ansi_term", version = "=0.11.0" },
]
skip = [
    
]
skip-tree = [
    { name = "graphql_client_codegen", version = "=0.8.0" },
]

[sources]
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"
# List of URLs for allowed Git repositories
allow-git = []
